export const CHANGE_START_STOP_STATE = "CHANGE_START_STOP_STATE";
export const CHANGE_PAUSE_RESUME_STATE = "CHANGE_PAUSE_RESUME_STATE";
export const INCREMENT_WORK = "INCREMENT_WORK";
export const SAVE_DIMENSIONS = "SAVE_DIMENSIONS";
export const SAVE_XY = "SAVE_XY";
export const SAVE_PROBABILITY = "SAVE_PROBABILITY";
export const SAVE_TRIES = "SAVE_TRIES";
